---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/koitoer/spring-cloud-sandbox
          searchPaths: config*
  application:
    name: eureka-server
server:
  port: 8001  # Eureka server port